### ISSUE TITLE
Cannot make add own world.

### ISSUE THREAD

**Issue by ExoOnix** [Brucewastaken/minecraft-server-on-heroku-template#10]
I deleted both the zip and world, and replaced with my worlds zip and folder. But it doesent change the world.

**Comment by Brucewastaken** [comment]
try replacing the files in the repo before building it in heroku and running setup.js, as it uploads the world.zip to the db. One way to solve this without creating a new app is to remove and re-add the postgres database, make sure that the config var for it is DATABASE_URL in settings, and build with only setup.js on and main.py off.

**Comment by ExoOnix** [comment]
The error is, that my world file is too big to push to GitHub. Is there any other method?

**Comment by Brucewastaken** [comment]
Sorry for the late reply, but you can install the desktop app which allows you to push larger files to the repo.

**Comment by FlightXKSP** [comment]
There is a 100mb limit.

**Comment by ExoOnix** [comment]
There is a 100mb limit.

**Comment by Brucewastaken** [comment]
You can try using the github LFS, but you should look more into it.

**Comment by ExoOnix** [comment]
Can you send me a git attributes file or should I just make it track zip and folders?

**Comment by ExoOnix** [comment]
Just tried using git lfs but I have to by content packs. Can I use any options other than github?

**Comment by Brucewastaken** [comment]
there's another way using heroku CLI to do it, and there's a short overview in the deploy tab if you choose heroku git or container registry. I'm not 100% sure if the limit is still present, but you can give it a shot.

**Comment by ExoOnix** [comment]
Sure I’ll try container registry.

**Comment by singham2000** [comment]
error: relation "files" does not exist

I am getting this error on Heroku while deploying the app.

**Comment by Brucewastaken** [comment]
> error: relation "files" does not exist
> 
> I am getting this error on Heroku while deploying the app.

Did you run setup.js? 
This error occurs because the table/database wasn't created. 
Check that a database is attached and run setup.js to create the table.
